source 'http://rubygems.org'

gem 'rails', '3.0.4'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'mongrel', ">=1.2.0pre2"
gem 'wirble'
gem 'hirb'
gem 'awesome_print'

group :notwindows do
  gem 'mysql2'
end

gem 'haml'
gem 'compass', ">= 0.10.6"
gem 'json'
gem 'uuidtools'
gem 'dragonfly'
gem 'aws-s3'
gem 'rack-cache', :require => 'rack/cache'
gem 'settingslogic'
gem 'roadie', :git => "git://github.com/Mange/roadie.git"
gem 'hpricot'
gem 'memcache-client'
gem 'nokogiri', '>=1.4.4'

gem 'pry'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
